### ISSUE TITLE
Criar layout Tela Default do Sitema

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#10]
Os menus laterais devem ser estáticos, assim como os menus principais de acesso da ferramenta. O layout que deverá  mudar a cada ação do usuário é somente da DIV PRINCIPAL, conforme imagem tela_default.

**Comment by lockland** [comment]
Pode validar o layout?

**Comment by franvareira** [comment]
Fiz download, mas não estou conseguindo rodar...estou indo pelo index.php que esta na raiz. É este neh?

**Comment by lockland** [comment]
Podemos fechar estar issue?

**Comment by franvareira** [comment]
Homologado.
