### ISSUE TITLE
Direcionar botão fechar da tela de inclusão e edição de usuários para a tela default de cadastro de usuários

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#16]

**Comment by lockland** [comment]
Não entendi essa demanda, anexa o print, quem sabe é melhor.

**Comment by franvareira** [comment]
Ao clicar no botão fechar esta direcionando para a tela default de apresentação
![botao_fechar](https://cloud.githubusercontent.com/assets/11817445/7800439/c4fea3be-02eb-11e5-897b-6871fdf51bc8.jpg)

![default](https://cloud.githubusercontent.com/assets/11817445/7800445/dea20c5c-02eb-11e5-905d-57070387f8d8.jpg)

Deverá voltar para tela default de cadastro de usuários. O mesmo ocorre para 
![tela_default_usuario](https://cloud.githubusercontent.com/assets/11817445/7800451/f953aa38-02eb-11e5-891b-19403f47cafe.jpg)
Clientes.

**Comment by lockland** [comment]
Isso tu mesmo pode fazer mudando a url nos arquivos .phtml.

Tenta fazer lá e se não conseguir tu me dá um tok

------------------------------------------------------
http://www.politicos.org.br

2015-05-25 14:40 GMT-03:00 franvareira <notifications@github.com>:
