### ISSUE TITLE
Nao esta validando usuário inativo

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#17]
segue print
![bug_usu](https://cloud.githubusercontent.com/assets/11817445/7849505/717a26e2-04ac-11e5-99de-5f456d463dfa.jpg)
![login_bug](https://cloud.githubusercontent.com/assets/11817445/7849509/7b401722-04ac-11e5-8407-17a185b3a3cb.jpg)
![logon_usu](https://cloud.githubusercontent.com/assets/11817445/7849512/81df37ac-04ac-11e5-8b13-75c5c9cdf0fc.jpg)

**Comment by lockland** [comment]
Blz, depois eu vejo isso. Aproveita e já abre uma outra issue para mim ver
a questão de o login ser unico


------------------------------------------------------
http://www.politicos.org.br
