### ISSUE TITLE
Integrar tela de cadastro de produtos

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#20]
-Integrar a tela de cadastro de produtos ao banco
-Criar links para navegação do sistema com a tela, menu e links rápidos.

**Comment by lockland** [comment]
# PARA QUE TUDO FUNCIONE É NECESSÁRIO EXECUTAR O SEGUINTE COMANDO:

```
mysql -u root -A < /var/www/sigec/docs/sigec.sql
```
