### ISSUE TITLE
Criar layout da tela de cadastro de usuários completa

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#3]
Criar estrutura da tela de cadastro de usuários conforme imagem cadastro_usuario.

**Comment by lockland** [comment]
Podemos homologar esta tarefa?

**Comment by franvareira** [comment]
Ainda, não quando definir os ajustes, já podemos homologar

2015-04-24 14:41 GMT-03:00 Sidney Souza <notifications@github.com>:

> Podemos homologar esta tarefa?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lockland/sigec/issues/3#issuecomment-96009623>.
>



-- 


*Atenciosamente,Francielle Vareira.*

**Comment by franvareira** [comment]
Homologado.

**Comment by franvareira** [comment]
Implementar na o backend para a pesquisa em filtros dos usuários.
