### ISSUE TITLE
Criar CRUD do cadastro de usuário

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#4]
Criar opções para incluir, editar, deletar e pesquisar. Ao inserir um usuário o mesmo deverá ter id, onde o mesmo só irá ser implementado na tela de edição do usuário.

**Comment by lockland** [comment]
As informações adicionadas a base de dados são realmente suficientes?

**Comment by franvareira** [comment]
Desculpe na tela de inclusao de usuário, esqueci de adicionar a lista de perfis para o administrador escolher.

**Comment by franvareira** [comment]
Tela para edição de usuário pronta, por favor implementar o backend para o estado inativo, ativo salvar em banco , e trazer tambem o estado ao clicar em "alterar".

**Comment by lockland** [comment]
Aguardando homologação

**Comment by lockland** [comment]
homologado
