### ISSUE TITLE
Criar layout de tela para edicao do cliente

### ISSUE THREAD

**Issue by franvareira** [lockland/sigec#8]
De acordo com a imagem edicao_cliente.

**Comment by lockland** [comment]
Tem alguma previsão para a conclusão desta tarefa?

**Comment by franvareira** [comment]
Irá, ser concluída no Domingo somente, sorry, é muita aula!

2015-04-24 14:40 GMT-03:00 Sidney Souza <notifications@github.com>:

> Tem alguma previsão para a conclusão desta tarefa?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lockland/sigec/issues/8#issuecomment-96009305>.
>



-- 


*Atenciosamente,Francielle Vareira.*

**Comment by franvareira** [comment]
Vou adicionar o input de seleção para Ativo ou Inativo na edição do usuário, quando estiver ok a tela, por favor colocar o backend para essa seleção ao gravar no banco.

**Comment by franvareira** [comment]
Tela esta pronta.
